# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json

# Learn more about building a configuration: https://promptfoo.dev/docs/configuration/guide

description: "evaluate youtube-note-to-obsidian skill"

prompts:
  - "summarise this youtube video {{youtube_url}}. Here are my comments: {{user_comments}}"
  - "save this to obsidian {{youtibe_url}}"
  

providers:
  - "google:gemini-2.5-flash"
  

tests:
  - vars:
      youtube_url: https://www.youtube.com/watch?v=dQw4w9WgXcQ
  - vars:
      youtube_url: https://www.youtube.com/watch?v=dQw4w9WgXcQ
      user_comments: "oh! you got me!!!"
  - vars:
      youtube_url: https://www.youtube.com/watch?v=aircAruvnKk
      user_comments: "interesting video on how JPEG actually works"
  #   assert:
  #     # For more information on assertions, see https://promptfoo.dev/docs/configuration/expected-outputs
  #
  #     # Make sure output contains the word "avocado"
  #     - type: icontains
  #       value: avocado
  #
  #     # Prefer shorter outputs
  #     - type: javascript
  #       value: 1 / (output.length + 1)
  #
  # - vars:
  #     topic: new york city
  #   assert:
  #     # For more information on model-graded evals, see https://promptfoo.dev/docs/configuration/expected-outputs/model-graded
  #     - type: llm-rubric
  #       value: ensure that the output is funny

